apiVersion: apps/v1
kind: Deployment
metadata:
  name: shalm
  labels:
    app: shalm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shalm
  template:
    metadata:
      labels:
        app: shalm
    spec:
      serviceAccountName: shalm
      containers:
      - name: shalm
        image: wonderix/shalm:latest
        {{ if .Values.image_pull_policy }}
        imagePullPolicy: {{ default .Values.image_pull_policy }}
        {{ end }}