apiVersion: v1
kind: ServiceAccount
metadata:
  name: shalm
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: shalm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: shalm
    namespace: {{ .Release.Namespace }}