---
apiVersion: v1
kind: Secret
metadata:
  name: {{ call .Methods.__secret_name | quote}}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{.Values.name}}
  password: {{.Values.password}}
