apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres
  namespace: default
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users: #@ { self.admin_user : [ "superuser" , "createdb"] , self.user : [] }
  databases: #@ { self.db : self.user }
  postgresql:
    version: "12"

