apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "master.fullname" . }}-init-scripts
  labels:
    app: "{{ template "mariadb.name" . }}"
    chart: "{{ template "mariadb.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    component: "master"
data:
  {{range $key, $val := .Values.databases}}
  {{ $key}}.sql : {{ $val | quote}}
  {{end}}
