name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: git checkout shalm
      uses: actions/checkout@v2
    - name: bump homebrew-tap
      run: |
        git clone "https://$GITHUB_ACTOR:${{ secrets.PUSH_TOKEN }}@github.com/wonderix/homebrew-tap.git" homebrew-tap
        make formula
        cd homebrew-tap
        git config --local user.email "wonderix@googlemail.com"
        git config --local user.name "GitHub Action"
        git commit -a -m "Bump to newest shalm release"
        git push
    - name: make docker-prepare
      run: make docker-prepare
    - name: docker push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wonderix/shalm
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        context: docker-context
        dockerfile: Dockerfile
    - name: make chart
      run: make chart
    - name: make binaries
      run: make binaries
    - name: upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/shalm-*.tgz
        asset_name: "Shalm chart"
        tag: ${{ github.ref }}
        file_glob: true
