name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - uses: actions/checkout@v1
    - name: make docker-prepare
      run: make docker-prepare
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wonderix/shalm
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        context: docker-context
        dockerfile: Dockerfile
    - name: Make chart
      run: make chart
    - name: Make binaries
      run: make binaries
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/shalm-*.tgz
        asset_name: "Shalm chart"
        tag: ${{ github.ref }}
        file_glob: true